apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "chart.fullname" . }}-node
  labels:
    app.kubernetes.io/part-of: csi-driver-oras
  {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: csi-oras-node
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: csi-oras-node
        app.kubernetes.io/part-of: csi-driver-oras
        role: csi-oras
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        env:
        - name: ADDRESS
          value: {{ quote .Values.node.driverRegistrar.env.address }}
        - name: DRIVER_REG_SOCK_PATH
          value: {{ quote .Values.node.driverRegistrar.env.driverRegSockPath }}
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.node.driverRegistrar.image.repository }}:{{ .Values.node.driverRegistrar.image.tag
          | default .Chart.AppVersion }}
        name: driver-registrar
        resources: {}
        volumeMounts:
        - mountPath: /csi/
          name: plugin-dir
        - mountPath: /registration/
          name: registration-dir
      - args:
        - --mode=node
        - --csi-endpoint=$(CSI_ENDPOINT)
        - --node-id=$(NODE_ID)
        - --root-dir=$(ROOT_DIR)
        - --plugin-data-dir=$(WORKING_DIR)
        - --mount-points-count=$(HANDLERS_COUNT)
        - --oras-logging=$(ORAS_LOGGING)
        - --enforce-namespaces=$(ENFORCE_NAMESPACES)
        env:
        - name: CSI_ENDPOINT
          value: {{ quote .Values.node.csiOrasPlugin.env.csiEndpoint }}
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ENFORCE_NAMESPACES
          valueFrom:
            configMapKeyRef:
              key: enforce_namespaces
              name: {{ include "chart.fullname" . }}-config
        - name: ROOT_DIR
          valueFrom:
            configMapKeyRef:
              key: csi_root_dir
              name: {{ include "chart.fullname" . }}-config
        - name: WORKING_DIR
          valueFrom:
            configMapKeyRef:
              key: driver_working_dir
              name: {{ include "chart.fullname" . }}-config
        - name: HANDLERS_COUNT
          valueFrom:
            configMapKeyRef:
              key: handlers_count
              name: {{ include "chart.fullname" . }}-config
        - name: ORAS_LOGGING
          valueFrom:
            configMapKeyRef:
              key: oras_logging
              name: {{ include "chart.fullname" . }}-config
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.node.csiOrasPlugin.image.repository }}:{{ .Values.node.csiOrasPlugin.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.node.csiOrasPlugin.imagePullPolicy }}
        name: csi-oras-plugin
        resources: {}
        securityContext: {{- toYaml .Values.node.csiOrasPlugin.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
          name: pods-mount-dir
        - mountPath: /dev
          name: device-dir
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccount: csi-oras-node-sa
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/csi.oras.land
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: pods-mount-dir
      - hostPath:
          path: /dev
        name: device-dir