apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "chart.fullname" . }}-oras-storage
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.oras.land