name: build oras-csi

on:
  pull_request: []
  push:
    branches:
    - main
    - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.18.1
    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Container
      run: make build

    - name: Deploy Container
      if: (github.event_name != 'pull_request')
      run: make push
